language: node_js

node_js:
  - 5.8
  - 5.9
  - 5.10

before_deploy:
  - bower i
  - npm run build
  - npm run cleanup

sudo: false

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: RLcuGA54UMZJoXlAaGDsRIPeiBf3Vks1SmtKPCbf802iRZSAAQCWJxqiAIOD1HEu/yyQsmJy1/9BhxYiuE/+aGH9jb316WwEhYbBwrotbXTpWa5SEdNpwYr4jBZL26SXt4Q9D1f/Dtk2nSVkhxLFjoL2gdkTTjskvVr+09oLPvGP/YRnKFpIS54tX2sGugXZ/XxNgjz6N2WWa3XLKe/qh5qN9xVhy6iovO8lR/sxIHA2le1BhNzaMt+oNPpMd5q7zHksqUevIhg2QhQrtD7kJEfilQXvcfgZzWf+S5BtMrOcLHtdZI3k567vi5BGGf+UjSjsbP5Ho3Ol1No6kjvrkRCBT9T0I5GbxfQ0SIfhE/7aSUTY939ROEbVWPnR25HphfXQi3Krj14j9H5Tze1iG4rKXOoVE9DkJre00UbNCod1WuW1XOlhrYqQLUxRrWhvuWuvj8konVdd92Sd73/1kmgzZagclOGQlgkE2Q0ZNgGJ7JEWNQ6/HBhzlmqXbVsOdiC/+a3rHEeaBb108LykhwxhFJZh9QOZYpV2lQly8UGoxpVCgcwQ3pIs5d8yJ8RFXFa+eTOnT90BdQ2BQZ1JX+Q6ggfhlWkB4hcDLbJzUc2yqBA2x4EKKEsMWLS9EahgdfRNPHc2ipXqDRU3NHSbdlttiZ8wjzv0C1mj27Hx4As=
  app: keo-app
  on:
    repo: Wildhoney/Keo
